2025-04-26 01:21:27.087 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 01:21:27.088 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 01:21:27.128 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 01:21:27.128 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 01:21:27.133 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 01:21:27.133 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 01:21:27.158 | d370e72a933d4e8580a02ac1438ae316 | INFO     | module_admin.controller.task_controller:get_task_list:57 - 获取成功
2025-04-26 01:21:27.165 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 01:25:58.099 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 01:25:58.100 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 01:25:58.136 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 01:25:58.137 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 01:25:58.140 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 01:25:58.140 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 01:26:06.721 | 78c33ca00330424c9f5858c3ccccfcca | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 01:29:45.889 | d899806de35f4a2b899453db3df1937b | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 01:30:01.646 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 01:30:14.610 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 01:30:14.611 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 01:30:14.650 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 01:30:14.651 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 01:30:14.656 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 01:30:14.656 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 01:30:14.678 | d134346f6a1649579bdc30b32f4eec7d | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 01:30:14.686 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 01:30:47.901 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 01:30:47.903 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 01:30:47.947 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 01:30:47.947 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 01:30:47.954 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 01:30:47.954 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 01:30:47.982 | a646688e449c4da281ce426611c007ea | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 01:30:47.992 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 01:30:57.410 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 01:30:57.410 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 01:30:57.453 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 01:30:57.454 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 01:30:57.462 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 01:30:57.463 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 01:30:57.490 | 0f829488ad864fa2af9f1ca22c6058e9 | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 01:30:57.567 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 01:31:09.432 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 01:31:09.432 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 01:31:09.471 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 01:31:09.472 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 01:31:09.478 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 01:31:09.478 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 01:31:09.501 | c38c3feef20b4efc8386c1cc836d23bf | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 01:31:09.508 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 01:31:17.400 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 01:31:17.400 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 01:31:17.439 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 01:31:17.439 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 01:31:17.445 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 01:31:17.445 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 01:31:17.470 | d94b687265bc45a28d287403ec40a037 | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 01:31:17.481 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 01:34:41.827 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 01:34:41.828 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 01:34:41.869 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 01:34:41.870 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 01:34:41.874 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 01:34:41.874 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 01:34:41.902 | 31bb31c2d4444db58991d4722e33f795 | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 01:34:41.910 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 01:34:56.188 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 01:34:56.189 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 01:34:56.230 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 01:34:56.231 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 01:34:56.236 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 01:34:56.236 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 01:34:56.263 | fb38c7fda85f4d009e0b50be142d2217 | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 01:34:56.339 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 01:35:08.769 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 01:35:08.770 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 01:35:08.810 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 01:35:08.811 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 01:35:08.815 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 01:35:08.816 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 01:35:08.842 | e9f60a783ab94658aded0bfd55f1c34b | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 01:35:08.852 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 01:36:17.770 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 01:36:17.770 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 01:36:17.811 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 01:36:17.811 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 01:36:17.817 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 01:36:17.817 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 01:36:17.843 | 703852ccf4cc408c841318293115fb6c | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 01:36:17.852 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 13:45:31.856 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 13:45:31.857 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 13:45:31.900 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 13:45:31.900 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 13:45:31.905 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 13:45:31.905 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 13:45:56.476 | 679a37f4e1a6470bbd1cacd0e798d299 | ERROR    | exceptions.handle:exception_handler:53 - (asyncmy.errors.IntegrityError) (1062, "Duplicate entry 'job-alice-bob-042' for key 'sys_task.PRIMARY'")
[SQL: INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_policy, status, run_status, task_progress, priority, create_by, create_time, update_by, update_time, remark) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('job-alice-bob-042', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_task.scheduler_test.job", "job_args": "", "job_kwargs": "", "job_name": "psi ... (162 characters truncated) ... r_test.job", "job_args": "", "job_kwargs": "", "job_name": "psi2", "job_parties": "[\\"party1\\",\\"party2\\"]", "job_dependencies": "[\\"psi3\\"]"}]', '1', '0/10 * * * * ?', '3', '1', 'not started', 0, '0', '', datetime.datetime(2025, 4, 26, 13, 45, 56, 406355), '', datetime.datetime(2025, 4, 26, 13, 45, 56, 406433), 'test')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):

  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x70b19e3fd2d0>
    │    └ <sqlalchemy.dialects.mysql.asyncmy.MySQLDialect_asyncmy object at 0x70b19e403c70>
    └ <sqlalchemy.engine.base.Connection object at 0x70b19eae2710>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ ('job-alice-bob-042', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
    │      │       └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
    │      └ <function AsyncAdapt_asyncmy_cursor.execute at 0x70b19e029c60>
    └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1975dfab0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 95, in execute
    return self.await_(self._execute_async(operation, parameters))
           │    │      │    │              │          └ ('job-alice-bob-042', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
           │    │      │    │              └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
           │    │      │    └ <function AsyncAdapt_asyncmy_cursor._execute_async at 0x70b19e029d80>
           │    │      └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1975dfab0>
           │    └ <member 'await_' of 'AsyncAdapt_asyncmy_cursor' objects>
           └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1975dfab0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           │       │             └ <coroutine object AsyncAdapt_asyncmy_cursor._execute_async at 0x70b19eac5540>
           │       └ <attribute 'parent' of 'greenlet.greenlet' objects>
           └ <_AsyncIoGreenlet object at 0x70b19f097140 (otid=0x70b19ebabd80) dead>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
                  └ <_cython_3_0_11.coroutine object at 0x70b19ea8ad40>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 107, in _execute_async
    result = await self._cursor.execute(operation, parameters)
                   │    │               │          └ ('job-alice-bob-042', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
                   │    │               └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
                   │    └ <member '_cursor' of 'AsyncAdapt_asyncmy_cursor' objects>
                   └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1975dfab0>
  File "asyncmy/cursors.pyx", line 179, in execute
    result = await self._query(query)
  File "asyncmy/cursors.pyx", line 364, in _query
    await conn.query(q)
  File "asyncmy/connection.pyx", line 496, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "asyncmy/connection.pyx", line 684, in _read_query_result
    await result.read()
  File "asyncmy/connection.pyx", line 1071, in read
    first_packet = await self.connection.read_packet()
  File "asyncmy/connection.pyx", line 646, in read_packet
    packet.raise_for_error()
  File "asyncmy/protocol.pyx", line 190, in asyncmy.protocol.MysqlPacket.raise_for_error
    cpdef raise_for_error(self):
  File "asyncmy/protocol.pyx", line 194, in asyncmy.protocol.MysqlPacket.raise_for_error
    errors.raise_mysql_exception(self._data)
    │      └ <cyfunction raise_mysql_exception at 0x70b19e0881e0>
    └ <module 'asyncmy.errors' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/asyncmy/errors.cpython...
  File "asyncmy/errors.pyx", line 128, in asyncmy.errors.raise_mysql_exception
    cpdef raise_mysql_exception(bytes data):
          └ <cyfunction raise_mysql_exception at 0x70b19e0881e0>
  File "asyncmy/errors.pyx", line 137, in asyncmy.errors.raise_mysql_exception
    raise error_class(errno, err_val)

asyncmy.errors.IntegrityError: (1062, "Duplicate entry 'job-alice-bob-042' for key 'sys_task.PRIMARY'")


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 4
               │     └ 13
               └ <function _main at 0x70b1a02ab5b0>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 4
           │    └ <function BaseProcess._bootstrap at 0x70b1a04365f0>
           └ <SpawnProcess name='SpawnProcess-1' parent=1708324 started>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x70b1a0435c60>
    └ <SpawnProcess name='SpawnProcess-1' parent=1708324 started>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x70b1a02af9a0>, 'target': <bound method Server.run of <uvicorn.server.Server obj...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=1708324 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-1' parent=1708324 started>
    │    └ <function subprocess_started at 0x70b19fd6d510>
    └ <SpawnProcess name='SpawnProcess-1' parent=1708324 started>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 9099)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x70b1a02afac0>>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 9099)>]
           │       │   │    └ <function Server.serve at 0x70b19fd6c790>
           │       │   └ <uvicorn.server.Server object at 0x70b1a02afac0>
           │       └ <function run at 0x70b1a02c69e0>
           └ <module 'asyncio' from '/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/asyncio/__i...
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x70b197bc2030>
           │    └ <cyfunction Loop.run_until_complete at 0x70b197c89b10>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x70b19ea1ebc0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x70b19eae06...
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x70b19ea...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x70b1a02afd90>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x70b19ea1ebc0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x70b19eae06...
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x70b19ea...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x70b19eae06...
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x70b19ea...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x70b19ea92f50>
          └ <fastapi.applications.FastAPI object at 0x70b1a02afd90>
> File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x70b19eac05e0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x70b19ea...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │    └ <middlewares.trace_middleware.middle.TraceASGIMiddleware object at 0x70b19ea92fe0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x70b19ea92f50>

  File "/disc/home/beng003/work/DAGScheduler/middlewares/trace_middleware/middle.py", line 62, in __call__
    await self.app(scope, handle_outgoing_receive, handle_outgoing_request)
          │    │   │      │                        └ <function TraceASGIMiddleware.__call__.<locals>.handle_outgoing_request at 0x70b19eac0790>
          │    │   │      └ <function RequestResponseCycle.receive at 0x70b19eac0700>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x70b19ea93010>
          └ <middlewares.trace_middleware.middle.TraceASGIMiddleware object at 0x70b19ea92fe0>

  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function TraceASGIMiddleware.__call__.<locals>.handle_outgoing_request at 0x70b19eac0790>
          │                            │    │    │     │      └ <function RequestResponseCycle.receive at 0x70b19eac0700>
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │                            │    │    └ <starlette.requests.Request object at 0x70b19eae0910>
          │                            │    └ <fastapi.routing.APIRouter object at 0x70b197b70f70>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x70b19ea93010>
          └ <function wrap_app_handling_exceptions at 0x70b19ef18940>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x70b19eac0820>
          │   │      └ <function RequestResponseCycle.receive at 0x70b19eac0700>
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          └ <fastapi.routing.APIRouter object at 0x70b197b70f70>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x70b19eac0820>
          │    │                │      └ <function RequestResponseCycle.receive at 0x70b19eac0700>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x70b197b70f70>>
          └ <fastapi.routing.APIRouter object at 0x70b197b70f70>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x70b19eac0820>
          │     │      │      └ <function RequestResponseCycle.receive at 0x70b19eac0700>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │     └ <function Route.handle at 0x70b19ef19fc0>
          └ APIRoute(path='/scheduler/task/add', name='add_task', methods=['POST'])
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x70b19eac0820>
          │    │   │      └ <function RequestResponseCycle.receive at 0x70b19eac0700>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │    └ <function request_response.<locals>.app at 0x70b197b7dbd0>
          └ APIRoute(path='/scheduler/task/add', name='add_task', methods=['POST'])
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x70b19eac0820>
          │                            │    │        │      └ <function RequestResponseCycle.receive at 0x70b19eac0700>
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │                            │    └ <starlette.requests.Request object at 0x70b19eae0a60>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x70b19eac08b0>
          └ <function wrap_app_handling_exceptions at 0x70b19ef18940>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x70b19eac0940>
          │   │      └ <function RequestResponseCycle.receive at 0x70b19eac0700>
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          └ <function request_response.<locals>.app.<locals>.app at 0x70b19eac08b0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x70b19eae0a60>
                     └ <function get_request_handler.<locals>.app at 0x70b197b7db40>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x70b19ef1bac0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'query_db': <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x70b19eae0eb0>, 'add_task': TaskModel(task_uid='job-alic...
                 │         └ <function add_task at 0x70b197b7c940>
                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[ModelField(field_info=Body(Pydant...

  File "/disc/home/beng003/work/DAGScheduler/module_admin/controller/task_controller.py", line 72, in add_task
    add_task_result = await TaskService.add_task_services(
                            │           └ <classmethod(<function TaskService.add_task_services at 0x70b197b7c160>)>
                            └ <class 'module_admin.service.task_service.TaskService'>

  File "/disc/home/beng003/work/DAGScheduler/module_admin/service/task_service.py", line 91, in add_task_services
    raise e

  File "/disc/home/beng003/work/DAGScheduler/module_admin/service/task_service.py", line 76, in add_task_services
    add_task = await TaskDao.add_task_dao(query_db, page_object)
                     │       │            │         └ TaskModel(task_uid='job-alice-bob-042', task_name='task2', task_initiator='alice', task_group='default', task_yaml=[JobModel(...
                     │       │            └ <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x70b19eae0eb0>
                     │       └ <classmethod(<function TaskDao.add_task_dao at 0x70b19c0f9990>)>
                     └ <class 'module_admin.dao.task_dao.TaskDao'>

  File "/disc/home/beng003/work/DAGScheduler/module_admin/dao/task_dao.py", line 134, in add_task_dao
    await db.flush()
          │  └ <function AsyncSession.flush at 0x70b19e1b0f70>
          └ <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x70b19eae0eb0>

  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 802, in flush
    await greenlet_spawn(self.sync_session.flush, objects=objects)
          │              │    │            │              └ None
          │              │    │            └ <function Session.flush at 0x70b19e0df910>
          │              │    └ <sqlalchemy.orm.session.Session object at 0x70b19eae0f70>
          │              └ <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x70b19eae0eb0>
          └ <function greenlet_spawn at 0x70b19ebfdbd0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
             │       │      └ None
             │       └ <method 'switch' of 'greenlet.greenlet' objects>
             └ <_AsyncIoGreenlet object at 0x70b19f097140 (otid=0x70b19ebabd80) dead>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4353, in flush
    self._flush(objects)
    │    │      └ None
    │    └ <function Session._flush at 0x70b19e0dfac0>
    └ <sqlalchemy.orm.session.Session object at 0x70b19eae0f70>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    with util.safe_reraise():
         │    └ <class 'sqlalchemy.util.langhelpers.safe_reraise'>
         └ <module 'sqlalchemy.util' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/__ini...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
          │         │              └ <traceback object at 0x70b197609140>
          │         └ <method 'with_traceback' of 'BaseException' objects>
          └ IntegrityError('(asyncmy.errors.IntegrityError) (1062, "Duplicate entry \'job-alice-bob-042\' for key \'sys_task.PRIMARY\'")')
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4449, in _flush
    flush_context.execute()
    │             └ <function UOWTransaction.execute at 0x70b19e0cdc60>
    └ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x70b19eae2e90>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
    │   │       └ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x70b19eae2e90>
    │   └ <function SaveUpdateAll.execute at 0x70b19e0ce560>
    └ SaveUpdateAll(Mapper[SysTask(sys_task)])
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    │    │         │               └ <function save_obj at 0x70b19e2a8940>
    │    │         └ <module 'sqlalchemy.orm.persistence' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy...
    │    └ <module 'sqlalchemy.util.preloaded' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/...
    └ <module 'sqlalchemy.util' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/__ini...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
    └ <function _emit_insert_statements at 0x70b19e2a9480>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
             │          └ <function Connection.execute at 0x70b19e551b40>
             └ <sqlalchemy.engine.base.Connection object at 0x70b19eae2710>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
           └ <bound method ClauseElement._execute_on_connection of <sqlalchemy.sql.dml.Insert object at 0x70b1975f6020>>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           │          └ <function Connection._execute_clauseelement at 0x70b19e551e10>
           └ <sqlalchemy.engine.base.Connection object at 0x70b19eae2710>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          │    └ <function Connection._execute_context at 0x70b19e551fc0>
          └ <sqlalchemy.engine.base.Connection object at 0x70b19eae2710>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
           │    └ <function Connection._exec_single_context at 0x70b19e552050>
           └ <sqlalchemy.engine.base.Connection object at 0x70b19eae2710>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
    │    └ <function Connection._handle_dbapi_exception at 0x70b19e552290>
    └ <sqlalchemy.engine.base.Connection object at 0x70b19eae2710>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
          │                    │              │                 └ IntegrityError(1062, "Duplicate entry 'job-alice-bob-042' for key 'sys_task.PRIMARY'")
          │                    │              └ (<class 'asyncmy.errors.IntegrityError'>, IntegrityError(1062, "Duplicate entry 'job-alice-bob-042' for key 'sys_task.PRIMARY...
          │                    └ <method 'with_traceback' of 'BaseException' objects>
          └ IntegrityError('(asyncmy.errors.IntegrityError) (1062, "Duplicate entry \'job-alice-bob-042\' for key \'sys_task.PRIMARY\'")')
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x70b19e3fd2d0>
    │    └ <sqlalchemy.dialects.mysql.asyncmy.MySQLDialect_asyncmy object at 0x70b19e403c70>
    └ <sqlalchemy.engine.base.Connection object at 0x70b19eae2710>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ ('job-alice-bob-042', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
    │      │       └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
    │      └ <function AsyncAdapt_asyncmy_cursor.execute at 0x70b19e029c60>
    └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1975dfab0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 95, in execute
    return self.await_(self._execute_async(operation, parameters))
           │    │      │    │              │          └ ('job-alice-bob-042', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
           │    │      │    │              └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
           │    │      │    └ <function AsyncAdapt_asyncmy_cursor._execute_async at 0x70b19e029d80>
           │    │      └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1975dfab0>
           │    └ <member 'await_' of 'AsyncAdapt_asyncmy_cursor' objects>
           └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1975dfab0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           │       │             └ <coroutine object AsyncAdapt_asyncmy_cursor._execute_async at 0x70b19eac5540>
           │       └ <attribute 'parent' of 'greenlet.greenlet' objects>
           └ <_AsyncIoGreenlet object at 0x70b19f097140 (otid=0x70b19ebabd80) dead>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
                  └ <_cython_3_0_11.coroutine object at 0x70b19ea8ad40>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 107, in _execute_async
    result = await self._cursor.execute(operation, parameters)
                   │    │               │          └ ('job-alice-bob-042', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
                   │    │               └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
                   │    └ <member '_cursor' of 'AsyncAdapt_asyncmy_cursor' objects>
                   └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1975dfab0>
  File "asyncmy/cursors.pyx", line 179, in execute
    result = await self._query(query)
  File "asyncmy/cursors.pyx", line 364, in _query
    await conn.query(q)
  File "asyncmy/connection.pyx", line 496, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "asyncmy/connection.pyx", line 684, in _read_query_result
    await result.read()
  File "asyncmy/connection.pyx", line 1071, in read
    first_packet = await self.connection.read_packet()
  File "asyncmy/connection.pyx", line 646, in read_packet
    packet.raise_for_error()
  File "asyncmy/protocol.pyx", line 190, in asyncmy.protocol.MysqlPacket.raise_for_error
    cpdef raise_for_error(self):
  File "asyncmy/protocol.pyx", line 194, in asyncmy.protocol.MysqlPacket.raise_for_error
    errors.raise_mysql_exception(self._data)
    │      └ <cyfunction raise_mysql_exception at 0x70b19e0881e0>
    └ <module 'asyncmy.errors' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/asyncmy/errors.cpython...
  File "asyncmy/errors.pyx", line 128, in asyncmy.errors.raise_mysql_exception
    cpdef raise_mysql_exception(bytes data):
          └ <cyfunction raise_mysql_exception at 0x70b19e0881e0>
  File "asyncmy/errors.pyx", line 137, in asyncmy.errors.raise_mysql_exception
    raise error_class(errno, err_val)

sqlalchemy.exc.IntegrityError: (asyncmy.errors.IntegrityError) (1062, "Duplicate entry 'job-alice-bob-042' for key 'sys_task.PRIMARY'")
[SQL: INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_policy, status, run_status, task_progress, priority, create_by, create_time, update_by, update_time, remark) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('job-alice-bob-042', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_task.scheduler_test.job", "job_args": "", "job_kwargs": "", "job_name": "psi ... (162 characters truncated) ... r_test.job", "job_args": "", "job_kwargs": "", "job_name": "psi2", "job_parties": "[\\"party1\\",\\"party2\\"]", "job_dependencies": "[\\"psi3\\"]"}]', '1', '0/10 * * * * ?', '3', '1', 'not started', 0, '0', '', datetime.datetime(2025, 4, 26, 13, 45, 56, 406355), '', datetime.datetime(2025, 4, 26, 13, 45, 56, 406433), 'test')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-04-26 13:46:02.856 | 1db8645f227143fd8096bd65f8728dd6 | ERROR    | exceptions.handle:exception_handler:53 - (asyncmy.errors.IntegrityError) (1062, "Duplicate entry 'job-alice-bob-043' for key 'sys_task.PRIMARY'")
[SQL: INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_policy, status, run_status, task_progress, priority, create_by, create_time, update_by, update_time, remark) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('job-alice-bob-043', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_task.scheduler_test.job", "job_args": "", "job_kwargs": "", "job_name": "psi ... (162 characters truncated) ... r_test.job", "job_args": "", "job_kwargs": "", "job_name": "psi2", "job_parties": "[\\"party1\\",\\"party2\\"]", "job_dependencies": "[\\"psi3\\"]"}]', '1', '0/10 * * * * ?', '3', '1', 'not started', 0, '0', '', datetime.datetime(2025, 4, 26, 13, 46, 2, 840186), '', datetime.datetime(2025, 4, 26, 13, 46, 2, 840238), 'test')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):

  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x70b19e3fd2d0>
    │    └ <sqlalchemy.dialects.mysql.asyncmy.MySQLDialect_asyncmy object at 0x70b19e403c70>
    └ <sqlalchemy.engine.base.Connection object at 0x70b1975f75b0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ ('job-alice-bob-043', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
    │      │       └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
    │      └ <function AsyncAdapt_asyncmy_cursor.execute at 0x70b19e029c60>
    └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1973770b0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 95, in execute
    return self.await_(self._execute_async(operation, parameters))
           │    │      │    │              │          └ ('job-alice-bob-043', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
           │    │      │    │              └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
           │    │      │    └ <function AsyncAdapt_asyncmy_cursor._execute_async at 0x70b19e029d80>
           │    │      └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1973770b0>
           │    └ <member 'await_' of 'AsyncAdapt_asyncmy_cursor' objects>
           └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1973770b0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           │       │             └ <coroutine object AsyncAdapt_asyncmy_cursor._execute_async at 0x70b197378cf0>
           │       └ <attribute 'parent' of 'greenlet.greenlet' objects>
           └ <_AsyncIoGreenlet object at 0x70b1973832c0 (otid=0x70b19ebabd80) dead>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
                  └ <_cython_3_0_11.coroutine object at 0x70b197517880>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 107, in _execute_async
    result = await self._cursor.execute(operation, parameters)
                   │    │               │          └ ('job-alice-bob-043', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
                   │    │               └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
                   │    └ <member '_cursor' of 'AsyncAdapt_asyncmy_cursor' objects>
                   └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1973770b0>
  File "asyncmy/cursors.pyx", line 179, in execute
    result = await self._query(query)
  File "asyncmy/cursors.pyx", line 364, in _query
    await conn.query(q)
  File "asyncmy/connection.pyx", line 496, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "asyncmy/connection.pyx", line 684, in _read_query_result
    await result.read()
  File "asyncmy/connection.pyx", line 1071, in read
    first_packet = await self.connection.read_packet()
  File "asyncmy/connection.pyx", line 646, in read_packet
    packet.raise_for_error()
  File "asyncmy/protocol.pyx", line 190, in asyncmy.protocol.MysqlPacket.raise_for_error
    cpdef raise_for_error(self):
  File "asyncmy/protocol.pyx", line 194, in asyncmy.protocol.MysqlPacket.raise_for_error
    errors.raise_mysql_exception(self._data)
    │      └ <cyfunction raise_mysql_exception at 0x70b19e0881e0>
    └ <module 'asyncmy.errors' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/asyncmy/errors.cpython...
  File "asyncmy/errors.pyx", line 128, in asyncmy.errors.raise_mysql_exception
    cpdef raise_mysql_exception(bytes data):
          └ <cyfunction raise_mysql_exception at 0x70b19e0881e0>
  File "asyncmy/errors.pyx", line 137, in asyncmy.errors.raise_mysql_exception
    raise error_class(errno, err_val)

asyncmy.errors.IntegrityError: (1062, "Duplicate entry 'job-alice-bob-043' for key 'sys_task.PRIMARY'")


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 4
               │     └ 13
               └ <function _main at 0x70b1a02ab5b0>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 4
           │    └ <function BaseProcess._bootstrap at 0x70b1a04365f0>
           └ <SpawnProcess name='SpawnProcess-1' parent=1708324 started>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x70b1a0435c60>
    └ <SpawnProcess name='SpawnProcess-1' parent=1708324 started>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x70b1a02af9a0>, 'target': <bound method Server.run of <uvicorn.server.Server obj...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=1708324 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-1' parent=1708324 started>
    │    └ <function subprocess_started at 0x70b19fd6d510>
    └ <SpawnProcess name='SpawnProcess-1' parent=1708324 started>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 9099)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x70b1a02afac0>>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 9099)>]
           │       │   │    └ <function Server.serve at 0x70b19fd6c790>
           │       │   └ <uvicorn.server.Server object at 0x70b1a02afac0>
           │       └ <function run at 0x70b1a02c69e0>
           └ <module 'asyncio' from '/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/asyncio/__i...
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x70b197bc2030>
           │    └ <cyfunction Loop.run_until_complete at 0x70b197c89b10>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x70b19ea1ebc0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x70b1975f5b...
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x70b1975...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x70b1a02afd90>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x70b19ea1ebc0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x70b1975f5b...
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x70b1975...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x70b1975f5b...
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x70b1975...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x70b19ea92f50>
          └ <fastapi.applications.FastAPI object at 0x70b1a02afd90>
> File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x70b197630280>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x70b1975...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │    └ <middlewares.trace_middleware.middle.TraceASGIMiddleware object at 0x70b19ea92fe0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x70b19ea92f50>

  File "/disc/home/beng003/work/DAGScheduler/middlewares/trace_middleware/middle.py", line 62, in __call__
    await self.app(scope, handle_outgoing_receive, handle_outgoing_request)
          │    │   │      │                        └ <function TraceASGIMiddleware.__call__.<locals>.handle_outgoing_request at 0x70b197334dc0>
          │    │   │      └ <function RequestResponseCycle.receive at 0x70b1974d1e10>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x70b19ea93010>
          └ <middlewares.trace_middleware.middle.TraceASGIMiddleware object at 0x70b19ea92fe0>

  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function TraceASGIMiddleware.__call__.<locals>.handle_outgoing_request at 0x70b197334dc0>
          │                            │    │    │     │      └ <function RequestResponseCycle.receive at 0x70b1974d1e10>
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │                            │    │    └ <starlette.requests.Request object at 0x70b1975f6890>
          │                            │    └ <fastapi.routing.APIRouter object at 0x70b197b70f70>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x70b19ea93010>
          └ <function wrap_app_handling_exceptions at 0x70b19ef18940>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x70b197334ee0>
          │   │      └ <function RequestResponseCycle.receive at 0x70b1974d1e10>
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          └ <fastapi.routing.APIRouter object at 0x70b197b70f70>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x70b197334ee0>
          │    │                │      └ <function RequestResponseCycle.receive at 0x70b1974d1e10>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x70b197b70f70>>
          └ <fastapi.routing.APIRouter object at 0x70b197b70f70>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x70b197334ee0>
          │     │      │      └ <function RequestResponseCycle.receive at 0x70b1974d1e10>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │     └ <function Route.handle at 0x70b19ef19fc0>
          └ APIRoute(path='/scheduler/task/add', name='add_task', methods=['POST'])
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x70b197334ee0>
          │    │   │      └ <function RequestResponseCycle.receive at 0x70b1974d1e10>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │    └ <function request_response.<locals>.app at 0x70b197b7dbd0>
          └ APIRoute(path='/scheduler/task/add', name='add_task', methods=['POST'])
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x70b197334ee0>
          │                            │    │        │      └ <function RequestResponseCycle.receive at 0x70b1974d1e10>
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          │                            │    └ <starlette.requests.Request object at 0x70b1975f7ee0>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x70b197334f70>
          └ <function wrap_app_handling_exceptions at 0x70b19ef18940>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x70b197335000>
          │   │      └ <function RequestResponseCycle.receive at 0x70b1974d1e10>
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 9099), 'cl...
          └ <function request_response.<locals>.app.<locals>.app at 0x70b197334f70>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x70b1975f7ee0>
                     └ <function get_request_handler.<locals>.app at 0x70b197b7db40>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x70b19ef1bac0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'query_db': <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x70b1975f7a00>, 'add_task': TaskModel(task_uid='job-alic...
                 │         └ <function add_task at 0x70b197b7c940>
                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[ModelField(field_info=Body(Pydant...

  File "/disc/home/beng003/work/DAGScheduler/module_admin/controller/task_controller.py", line 72, in add_task
    add_task_result = await TaskService.add_task_services(
                            │           └ <classmethod(<function TaskService.add_task_services at 0x70b197b7c160>)>
                            └ <class 'module_admin.service.task_service.TaskService'>

  File "/disc/home/beng003/work/DAGScheduler/module_admin/service/task_service.py", line 91, in add_task_services
    raise e

  File "/disc/home/beng003/work/DAGScheduler/module_admin/service/task_service.py", line 76, in add_task_services
    add_task = await TaskDao.add_task_dao(query_db, page_object)
                     │       │            │         └ TaskModel(task_uid='job-alice-bob-043', task_name='task2', task_initiator='alice', task_group='default', task_yaml=[JobModel(...
                     │       │            └ <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x70b1975f7a00>
                     │       └ <classmethod(<function TaskDao.add_task_dao at 0x70b19c0f9990>)>
                     └ <class 'module_admin.dao.task_dao.TaskDao'>

  File "/disc/home/beng003/work/DAGScheduler/module_admin/dao/task_dao.py", line 134, in add_task_dao
    await db.flush()
          │  └ <function AsyncSession.flush at 0x70b19e1b0f70>
          └ <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x70b1975f7a00>

  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 802, in flush
    await greenlet_spawn(self.sync_session.flush, objects=objects)
          │              │    │            │              └ None
          │              │    │            └ <function Session.flush at 0x70b19e0df910>
          │              │    └ <sqlalchemy.orm.session.Session object at 0x70b1975f7940>
          │              └ <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x70b1975f7a00>
          └ <function greenlet_spawn at 0x70b19ebfdbd0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
             │       │      └ None
             │       └ <method 'switch' of 'greenlet.greenlet' objects>
             └ <_AsyncIoGreenlet object at 0x70b1973832c0 (otid=0x70b19ebabd80) dead>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4353, in flush
    self._flush(objects)
    │    │      └ None
    │    └ <function Session._flush at 0x70b19e0dfac0>
    └ <sqlalchemy.orm.session.Session object at 0x70b1975f7940>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    with util.safe_reraise():
         │    └ <class 'sqlalchemy.util.langhelpers.safe_reraise'>
         └ <module 'sqlalchemy.util' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/__ini...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
          │         │              └ <traceback object at 0x70b197382e00>
          │         └ <method 'with_traceback' of 'BaseException' objects>
          └ IntegrityError('(asyncmy.errors.IntegrityError) (1062, "Duplicate entry \'job-alice-bob-043\' for key \'sys_task.PRIMARY\'")')
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4449, in _flush
    flush_context.execute()
    │             └ <function UOWTransaction.execute at 0x70b19e0cdc60>
    └ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x70b1975f7490>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
    │   │       └ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x70b1975f7490>
    │   └ <function SaveUpdateAll.execute at 0x70b19e0ce560>
    └ SaveUpdateAll(Mapper[SysTask(sys_task)])
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    │    │         │               └ <function save_obj at 0x70b19e2a8940>
    │    │         └ <module 'sqlalchemy.orm.persistence' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy...
    │    └ <module 'sqlalchemy.util.preloaded' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/...
    └ <module 'sqlalchemy.util' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/__ini...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
    └ <function _emit_insert_statements at 0x70b19e2a9480>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
             │          └ <function Connection.execute at 0x70b19e551b40>
             └ <sqlalchemy.engine.base.Connection object at 0x70b1975f75b0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
           └ <bound method ClauseElement._execute_on_connection of <sqlalchemy.sql.dml.Insert object at 0x70b1975f6020>>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           │          └ <function Connection._execute_clauseelement at 0x70b19e551e10>
           └ <sqlalchemy.engine.base.Connection object at 0x70b1975f75b0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          │    └ <function Connection._execute_context at 0x70b19e551fc0>
          └ <sqlalchemy.engine.base.Connection object at 0x70b1975f75b0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
           │    └ <function Connection._exec_single_context at 0x70b19e552050>
           └ <sqlalchemy.engine.base.Connection object at 0x70b1975f75b0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
    │    └ <function Connection._handle_dbapi_exception at 0x70b19e552290>
    └ <sqlalchemy.engine.base.Connection object at 0x70b1975f75b0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
          │                    │              │                 └ IntegrityError(1062, "Duplicate entry 'job-alice-bob-043' for key 'sys_task.PRIMARY'")
          │                    │              └ (<class 'asyncmy.errors.IntegrityError'>, IntegrityError(1062, "Duplicate entry 'job-alice-bob-043' for key 'sys_task.PRIMARY...
          │                    └ <method 'with_traceback' of 'BaseException' objects>
          └ IntegrityError('(asyncmy.errors.IntegrityError) (1062, "Duplicate entry \'job-alice-bob-043\' for key \'sys_task.PRIMARY\'")')
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x70b19e3fd2d0>
    │    └ <sqlalchemy.dialects.mysql.asyncmy.MySQLDialect_asyncmy object at 0x70b19e403c70>
    └ <sqlalchemy.engine.base.Connection object at 0x70b1975f75b0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ ('job-alice-bob-043', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
    │      │       └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
    │      └ <function AsyncAdapt_asyncmy_cursor.execute at 0x70b19e029c60>
    └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1973770b0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 95, in execute
    return self.await_(self._execute_async(operation, parameters))
           │    │      │    │              │          └ ('job-alice-bob-043', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
           │    │      │    │              └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
           │    │      │    └ <function AsyncAdapt_asyncmy_cursor._execute_async at 0x70b19e029d80>
           │    │      └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1973770b0>
           │    └ <member 'await_' of 'AsyncAdapt_asyncmy_cursor' objects>
           └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1973770b0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           │       │             └ <coroutine object AsyncAdapt_asyncmy_cursor._execute_async at 0x70b197378cf0>
           │       └ <attribute 'parent' of 'greenlet.greenlet' objects>
           └ <_AsyncIoGreenlet object at 0x70b1973832c0 (otid=0x70b19ebabd80) dead>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
                  └ <_cython_3_0_11.coroutine object at 0x70b197517880>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 107, in _execute_async
    result = await self._cursor.execute(operation, parameters)
                   │    │               │          └ ('job-alice-bob-043', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
                   │    │               └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
                   │    └ <member '_cursor' of 'AsyncAdapt_asyncmy_cursor' objects>
                   └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x70b1973770b0>
  File "asyncmy/cursors.pyx", line 179, in execute
    result = await self._query(query)
  File "asyncmy/cursors.pyx", line 364, in _query
    await conn.query(q)
  File "asyncmy/connection.pyx", line 496, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "asyncmy/connection.pyx", line 684, in _read_query_result
    await result.read()
  File "asyncmy/connection.pyx", line 1071, in read
    first_packet = await self.connection.read_packet()
  File "asyncmy/connection.pyx", line 646, in read_packet
    packet.raise_for_error()
  File "asyncmy/protocol.pyx", line 190, in asyncmy.protocol.MysqlPacket.raise_for_error
    cpdef raise_for_error(self):
  File "asyncmy/protocol.pyx", line 194, in asyncmy.protocol.MysqlPacket.raise_for_error
    errors.raise_mysql_exception(self._data)
    │      └ <cyfunction raise_mysql_exception at 0x70b19e0881e0>
    └ <module 'asyncmy.errors' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/asyncmy/errors.cpython...
  File "asyncmy/errors.pyx", line 128, in asyncmy.errors.raise_mysql_exception
    cpdef raise_mysql_exception(bytes data):
          └ <cyfunction raise_mysql_exception at 0x70b19e0881e0>
  File "asyncmy/errors.pyx", line 137, in asyncmy.errors.raise_mysql_exception
    raise error_class(errno, err_val)

sqlalchemy.exc.IntegrityError: (asyncmy.errors.IntegrityError) (1062, "Duplicate entry 'job-alice-bob-043' for key 'sys_task.PRIMARY'")
[SQL: INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_policy, status, run_status, task_progress, priority, create_by, create_time, update_by, update_time, remark) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('job-alice-bob-043', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_task.scheduler_test.job", "job_args": "", "job_kwargs": "", "job_name": "psi ... (162 characters truncated) ... r_test.job", "job_args": "", "job_kwargs": "", "job_name": "psi2", "job_parties": "[\\"party1\\",\\"party2\\"]", "job_dependencies": "[\\"psi3\\"]"}]', '1', '0/10 * * * * ?', '3', '1', 'not started', 0, '0', '', datetime.datetime(2025, 4, 26, 13, 46, 2, 840186), '', datetime.datetime(2025, 4, 26, 13, 46, 2, 840238), 'test')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-04-26 13:46:06.766 | d05b01e75c6f4700848fd477008158cc | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 13:51:11.253 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 13:51:11.254 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 13:51:11.285 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 13:51:11.286 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 13:51:11.289 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 13:51:11.290 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 13:52:32.787 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 13:52:32.788 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 13:52:32.816 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 13:52:32.816 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 13:52:32.820 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 13:52:32.820 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 13:53:07.035 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 13:53:07.969 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 13:53:07.970 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 13:53:08.006 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 13:53:08.006 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 13:53:08.011 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 13:53:08.012 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 13:55:00.508 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 13:55:01.455 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 13:55:01.455 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 13:55:01.493 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 13:55:01.494 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 13:55:01.498 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 13:55:01.499 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 13:55:17.114 | 3aab65fae4fc4cec87cb67cc57e58bc8 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 14:02:48.497 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 14:02:48.497 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 14:02:48.531 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 14:02:48.531 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 14:02:48.535 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 14:02:48.535 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 14:05:49.021 | a78bd8fb07224bf48bea5f5907bf6fa9 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 14:09:50.760 | d127eb78906d4057bbf31ca3aa8cc595 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 14:14:25.310 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 14:14:25.310 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 14:14:25.325 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 14:14:25.325 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 14:14:25.327 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 14:14:25.327 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 14:14:31.422 | 3c4f1bedcac54f2a939f4b325dbb2607 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 14:26:43.269 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 14:47:43.482 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 14:47:43.482 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 14:47:43.501 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 14:47:43.502 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 14:47:43.507 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 14:47:43.508 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 14:47:43.541 | 13a3f32f9c154f37a3bc8747f3543987 | ERROR    | exceptions.handle:exception_handler:53 - (asyncmy.errors.IntegrityError) (1062, "Duplicate entry 'job-alice-bob-048' for key 'sys_task.PRIMARY'")
[SQL: INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_policy, status, run_status, task_progress, priority, create_by, create_time, update_by, update_time, remark) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('job-alice-bob-048', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_task.scheduler_test.job", "job_args": "", "job_kwargs": "", "job_name": "psi ... (162 characters truncated) ... r_test.job", "job_args": "", "job_kwargs": "", "job_name": "psi2", "job_parties": "[\\"party1\\",\\"party2\\"]", "job_dependencies": "[\\"psi3\\"]"}]', '1', '0/10 * * * * ?', '3', '1', 'not started', 0, '0', 'admin', datetime.datetime(2025, 4, 26, 14, 47, 43, 520159), '', datetime.datetime(2025, 4, 26, 14, 47, 43, 520196), 'test')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):

  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x731655283490>
    │    └ <sqlalchemy.dialects.mysql.asyncmy.MySQLDialect_asyncmy object at 0x7316552e4880>
    └ <sqlalchemy.engine.base.Connection object at 0x731651d440a0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ ('job-alice-bob-048', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
    │      │       └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
    │      └ <function AsyncAdapt_asyncmy_cursor.execute at 0x731654ec7d00>
    └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x731651d32bb0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 95, in execute
    return self.await_(self._execute_async(operation, parameters))
           │    │      │    │              │          └ ('job-alice-bob-048', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
           │    │      │    │              └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
           │    │      │    └ <function AsyncAdapt_asyncmy_cursor._execute_async at 0x731654ec7e20>
           │    │      └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x731651d32bb0>
           │    └ <member 'await_' of 'AsyncAdapt_asyncmy_cursor' objects>
           └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x731651d32bb0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           │       │             └ <coroutine object AsyncAdapt_asyncmy_cursor._execute_async at 0x731651d9c660>
           │       └ <attribute 'parent' of 'greenlet.greenlet' objects>
           └ <_AsyncIoGreenlet object at 0x731651e33080 (otid=0x7316557649c0) dead>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
                  └ <_cython_3_0_11.coroutine object at 0x731651d6cc20>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 107, in _execute_async
    result = await self._cursor.execute(operation, parameters)
                   │    │               │          └ ('job-alice-bob-048', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
                   │    │               └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
                   │    └ <member '_cursor' of 'AsyncAdapt_asyncmy_cursor' objects>
                   └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x731651d32bb0>
  File "asyncmy/cursors.pyx", line 179, in execute
    result = await self._query(query)
  File "asyncmy/cursors.pyx", line 364, in _query
    await conn.query(q)
  File "asyncmy/connection.pyx", line 496, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "asyncmy/connection.pyx", line 684, in _read_query_result
    await result.read()
  File "asyncmy/connection.pyx", line 1071, in read
    first_packet = await self.connection.read_packet()
  File "asyncmy/connection.pyx", line 646, in read_packet
    packet.raise_for_error()
  File "asyncmy/protocol.pyx", line 190, in asyncmy.protocol.MysqlPacket.raise_for_error
    cpdef raise_for_error(self):
  File "asyncmy/protocol.pyx", line 194, in asyncmy.protocol.MysqlPacket.raise_for_error
    errors.raise_mysql_exception(self._data)
    │      └ <cyfunction raise_mysql_exception at 0x731656d4cc70>
    └ <module 'asyncmy.errors' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/asyncmy/errors.cpython...
  File "asyncmy/errors.pyx", line 128, in asyncmy.errors.raise_mysql_exception
    cpdef raise_mysql_exception(bytes data):
          └ <cyfunction raise_mysql_exception at 0x731656d4cc70>
  File "asyncmy/errors.pyx", line 137, in asyncmy.errors.raise_mysql_exception
    raise error_class(errno, err_val)

asyncmy.errors.IntegrityError: (1062, "Duplicate entry 'job-alice-bob-048' for key 'sys_task.PRIMARY'")


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/disc/home/beng003/.trae-server/extensions/ms-python.python-2025.4.0-universal/python_files/vscode_pytest/run_pytest_script.py", line 64, in <module>
    pytest.main(arg_array)
    │      │    └ ['-vvv', '-s', '-p', 'vscode_pytest', '--rootdir=/disc/home/beng003/work/DAGScheduler', '/disc/home/beng003/work/DAGScheduler...
    │      └ <function main at 0x731657677e20>
    └ <module 'pytest' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pytest/__init__.py'>

  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
         │                │      │    │                          └ <_pytest.config.Config object at 0x7316574ce890>
         │                │      │    └ <HookCaller 'pytest_cmdline_main'>
         │                │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7316574ce9e0>
         │                └ <_pytest.config.Config object at 0x7316574ce890>
         └ <enum 'ExitCode'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'config': <_pytest.config.Config object at 0x7316574ce890>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_cmdline_main'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_cmdline_main'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_cmdline_main'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7316574ce890>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7316579d3760>
           └ <_pytest.config.PytestPluginManager object at 0x731657c17f70>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7316574ce890>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/s...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7316576eb6d0>
           │            └ <_pytest.config.Config object at 0x7316574ce890>
           └ <function wrap_session at 0x7316576eb5b0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session  exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>
    │       │            │    └ <_pytest.config.Config object at 0x7316574ce890>
    │       │            └ <function _main at 0x7316576eb6d0>
    │       └ <ExitCode.OK: 0>
    └ <Session  exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session  exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>
    │      │    └ <HookCaller 'pytest_runtestloop'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7316574ce9e0>
    └ <_pytest.config.Config object at 0x7316574ce890>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'session': <Session  exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtestloop'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtestloop'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtestloop'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session  exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7316579d3760>
           └ <_pytest.config.PytestPluginManager object at 0x731657c17f70>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session  exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/s...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │                                        │              └ None
    │    │                                        └ <Function test_add_task>
    │    └ <member 'config' of 'Node' objects>
    └ <Function test_add_task>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'item': <Function test_add_task>, 'nextitem': None}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_protocol'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_protocol'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_add_task>, 'nextitem': None}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7316579d3760>
           └ <_pytest.config.PytestPluginManager object at 0x731657c17f70>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_add_task>, None]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3....
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
    │               │              └ None
    │               └ <Function test_add_task>
    └ <function runtestprotocol at 0x7316576ea950>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ True
    │       │      │               └ <Function test_add_task>
    │       │      └ <function call_and_report at 0x7316576ead40>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'tests/test_module_admin/test_controller/test_task_controller.py::test_add_task' when='setup' outcome='passed'>]
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7316576eb010>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: TResult | None = func()
            │                └ <function call_and_report.<locals>.<lambda> at 0x731651e1f9a0>
            └ +TResult
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
            │                 │       └ {}
            │                 └ <Function test_add_task>
            └ <HookCaller 'pytest_runtest_call'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ False
           │    │         │    │     │    │                  └ {'item': <Function test_add_task>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_call'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_add_task>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7316579d3760>
           └ <_pytest.config.PytestPluginManager object at 0x731657c17f70>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_add_task>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3....
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/runner.py", line 174, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7316575f3a30>
    └ <Function test_add_task>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_add_task>
    │    └ <property object at 0x7316576a61b0>
    └ <Function test_add_task>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'pyfuncitem': <Function test_add_task>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_pyfunc_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_pyfunc_call'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_add_task>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7316579d3760>
           └ <_pytest.config.PytestPluginManager object at 0x731657c17f70>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_add_task>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='anyio', plugin=<module 'anyio.pytest_plugin' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/pyth...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/anyio/pytest_plugin.py", line 160, in pytest_pyfunc_call
    runner.run_test(pyfuncitem.obj, testargs)
    │      │        │          │    └ {'async_client': <httpx.AsyncClient object at 0x731651cdcd00>}
    │      │        │          └ <property object at 0x7316575fb380>
    │      │        └ <Function test_add_task>
    │      └ <function TestRunner.run_test at 0x731651eaf5b0>
    └ <anyio._backends._asyncio.TestRunner object at 0x731651e37d00>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2273, in run_test
    self.get_loop().run_until_complete(
    │    └ <function TestRunner.get_loop at 0x731651eaf1c0>
    └ <anyio._backends._asyncio.TestRunner object at 0x731651e37d00>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7316570dd120>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7316570dec20>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x73165707e5f0>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2200, in _run_tests_and_fixtures
    retval = await coro
                   └ <coroutine object test_add_task at 0x731651e82880>

  File "/disc/home/beng003/work/DAGScheduler/tests/test_module_admin/test_controller/test_task_controller.py", line 54, in test_add_task
    response = await async_client.post("/scheduler/task/add", json=task_data)
                     │            │                                └ {'task_uid': 'job-alice-bob-048', 'task_name': 'task2', 'task_initiator': 'alice', 'task_group': 'default', 'task_yaml': [{'j...
                     │            └ <function AsyncClient.post at 0x731652b01fc0>
                     └ <httpx.AsyncClient object at 0x731651cdcd00>

  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1859, in post
    return await self.request(
                 │    └ <function AsyncClient.request at 0x731652b01a20>
                 └ <httpx.AsyncClient object at 0x731651cdcd00>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
                 │    │    │             │                      └ <httpx._client.UseClientDefault object at 0x731652c69c60>
                 │    │    │             └ <httpx._client.UseClientDefault object at 0x731652c69c60>
                 │    │    └ <Request('POST', 'http://localhost:9099/scheduler/task/add')>
                 │    └ <function AsyncClient.send at 0x731652b01bd0>
                 └ <httpx.AsyncClient object at 0x731651cdcd00>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
                     │    └ <function AsyncClient._send_handling_auth at 0x731652b01c60>
                     └ <httpx.AsyncClient object at 0x731651cdcd00>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
                     │    └ <function AsyncClient._send_handling_redirects at 0x731652b01cf0>
                     └ <httpx.AsyncClient object at 0x731651cdcd00>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
                     │    │                    └ <Request('POST', 'http://localhost:9099/scheduler/task/add')>
                     │    └ <function AsyncClient._send_single_request at 0x731652b01d80>
                     └ <httpx.AsyncClient object at 0x731651cdcd00>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
                     │         │                    └ <Request('POST', 'http://localhost:9099/scheduler/task/add')>
                     │         └ <function ASGITransport.handle_async_request at 0x731652af6440>
                     └ <httpx.ASGITransport object at 0x731651cdd660>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/httpx/_transports/asgi.py", line 170, in handle_async_request
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ASGITransport.handle_async_request.<locals>.send at 0x731651eb4ee0>
          │    │   │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x731651eb4dc0>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │    └ <fastapi.applications.FastAPI object at 0x73165620ad40>
          └ <httpx.ASGITransport object at 0x731651cdd660>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <function ASGITransport.handle_async_request.<locals>.send at 0x731651eb4ee0>
                           │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x731651eb4dc0>
                           └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function ASGITransport.handle_async_request.<locals>.send at 0x731651eb4ee0>
          │    │                │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x731651eb4dc0>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x731651cdcc10>
          └ <fastapi.applications.FastAPI object at 0x73165620ad40>
> File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x731651eb5000>
          │    │   │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x731651eb4dc0>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │    └ <middlewares.trace_middleware.middle.TraceASGIMiddleware object at 0x731651cdcb80>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x731651cdcc10>

  File "/disc/home/beng003/work/DAGScheduler/middlewares/trace_middleware/middle.py", line 62, in __call__
    await self.app(scope, handle_outgoing_receive, handle_outgoing_request)
          │    │   │      │                        └ <function TraceASGIMiddleware.__call__.<locals>.handle_outgoing_request at 0x731651eb5b40>
          │    │   │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x731651eb5a20>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x731651cdcb50>
          └ <middlewares.trace_middleware.middle.TraceASGIMiddleware object at 0x731651cdcb80>

  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function TraceASGIMiddleware.__call__.<locals>.handle_outgoing_request at 0x731651eb5b40>
          │                            │    │    │     │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x731651eb5a20>
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │                            │    │    └ <starlette.requests.Request object at 0x731651cde2f0>
          │                            │    └ <fastapi.routing.APIRouter object at 0x731652816e00>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x731651cdcb50>
          └ <function wrap_app_handling_exceptions at 0x731655812830>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x731651eb5c60>
          │   │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x731651eb5a20>
          │   └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          └ <fastapi.routing.APIRouter object at 0x731652816e00>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x731651eb5c60>
          │    │                │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x731651eb5a20>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x731652816e00>>
          └ <fastapi.routing.APIRouter object at 0x731652816e00>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x731651eb5c60>
          │     │      │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x731651eb5a20>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │     └ <function Route.handle at 0x731655813eb0>
          └ APIRoute(path='/scheduler/task/add', name='add_task', methods=['POST'])
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x731651eb5c60>
          │    │   │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x731651eb5a20>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │    └ <function request_response.<locals>.app at 0x731652863c70>
          └ APIRoute(path='/scheduler/task/add', name='add_task', methods=['POST'])
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x731651eb5c60>
          │                            │    │        │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x731651eb5a20>
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │                            │    └ <starlette.requests.Request object at 0x731651cde440>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x731651eb4f70>
          └ <function wrap_app_handling_exceptions at 0x731655812830>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x731651eb5090>
          │   │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x731651eb5a20>
          │   └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          └ <function request_response.<locals>.app.<locals>.app at 0x731651eb4f70>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x731651cde440>
                     └ <function get_request_handler.<locals>.app at 0x731652863be0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x73165583da20>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'query_db': <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x731651cde890>, 'add_task': TaskModel(task_uid='job-alic...
                 │         └ <function add_task at 0x7316528629e0>
                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[ModelField(field_info=Body(Pydant...

  File "/disc/home/beng003/work/DAGScheduler/module_admin/controller/task_controller.py", line 72, in add_task
    add_task_result = await TaskService.add_task_services(
                            │           └ <classmethod(<function TaskService.add_task_services at 0x731652862290>)>
                            └ <class 'module_admin.service.task_service.TaskService'>

  File "/disc/home/beng003/work/DAGScheduler/module_admin/service/task_service.py", line 102, in add_task_services
    raise e

  File "/disc/home/beng003/work/DAGScheduler/module_admin/service/task_service.py", line 83, in add_task_services
    add_task = await TaskDao.add_task_dao(query_db, page_object)
                     │       │            │         └ TaskModel(task_uid='job-alice-bob-048', task_name='task2', task_initiator='alice', task_group='default', task_yaml=[JobModel(...
                     │       │            └ <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x731651cde890>
                     │       └ <classmethod(<function TaskDao.add_task_dao at 0x731652dbe170>)>
                     └ <class 'module_admin.dao.task_dao.TaskDao'>

  File "/disc/home/beng003/work/DAGScheduler/module_admin/dao/task_dao.py", line 134, in add_task_dao
    await db.flush()
          │  └ <function AsyncSession.flush at 0x731654e4b010>
          └ <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x731651cde890>

  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 802, in flush
    await greenlet_spawn(self.sync_session.flush, objects=objects)
          │              │    │            │              └ None
          │              │    │            └ <function Session.flush at 0x731654f91a20>
          │              │    └ <sqlalchemy.orm.session.Session object at 0x731651cde950>
          │              └ <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x731651cde890>
          └ <function greenlet_spawn at 0x7316557879a0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
             │       │      └ None
             │       └ <method 'switch' of 'greenlet.greenlet' objects>
             └ <_AsyncIoGreenlet object at 0x731651e33080 (otid=0x7316557649c0) dead>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4353, in flush
    self._flush(objects)
    │    │      └ None
    │    └ <function Session._flush at 0x731654f91bd0>
    └ <sqlalchemy.orm.session.Session object at 0x731651cde950>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    with util.safe_reraise():
         │    └ <class 'sqlalchemy.util.langhelpers.safe_reraise'>
         └ <module 'sqlalchemy.util' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/__ini...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
          │         │              └ <traceback object at 0x731651d876c0>
          │         └ <method 'with_traceback' of 'BaseException' objects>
          └ IntegrityError('(asyncmy.errors.IntegrityError) (1062, "Duplicate entry \'job-alice-bob-048\' for key \'sys_task.PRIMARY\'")')
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4449, in _flush
    flush_context.execute()
    │             └ <function UOWTransaction.execute at 0x731654f63d00>
    └ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x731651d44d90>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
    │   │       └ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x731651d44d90>
    │   └ <function SaveUpdateAll.execute at 0x731654f78670>
    └ SaveUpdateAll(Mapper[SysTask(sys_task)])
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    │    │         │               └ <function save_obj at 0x731654f269e0>
    │    │         └ <module 'sqlalchemy.orm.persistence' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy...
    │    └ <module 'sqlalchemy.util.preloaded' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/...
    └ <module 'sqlalchemy.util' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/__ini...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
    └ <function _emit_insert_statements at 0x731654f27520>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
             │          └ <function Connection.execute at 0x731655203d00>
             └ <sqlalchemy.engine.base.Connection object at 0x731651d440a0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
           └ <bound method ClauseElement._execute_on_connection of <sqlalchemy.sql.dml.Insert object at 0x731651d44a30>>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           │          └ <function Connection._execute_clauseelement at 0x731655204040>
           └ <sqlalchemy.engine.base.Connection object at 0x731651d440a0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          │    └ <function Connection._execute_context at 0x7316552041f0>
          └ <sqlalchemy.engine.base.Connection object at 0x731651d440a0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
           │    └ <function Connection._exec_single_context at 0x731655204280>
           └ <sqlalchemy.engine.base.Connection object at 0x731651d440a0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
    │    └ <function Connection._handle_dbapi_exception at 0x7316552044c0>
    └ <sqlalchemy.engine.base.Connection object at 0x731651d440a0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
          │                    │              │                 └ IntegrityError(1062, "Duplicate entry 'job-alice-bob-048' for key 'sys_task.PRIMARY'")
          │                    │              └ (<class 'asyncmy.errors.IntegrityError'>, IntegrityError(1062, "Duplicate entry 'job-alice-bob-048' for key 'sys_task.PRIMARY...
          │                    └ <method 'with_traceback' of 'BaseException' objects>
          └ IntegrityError('(asyncmy.errors.IntegrityError) (1062, "Duplicate entry \'job-alice-bob-048\' for key \'sys_task.PRIMARY\'")')
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x731655283490>
    │    └ <sqlalchemy.dialects.mysql.asyncmy.MySQLDialect_asyncmy object at 0x7316552e4880>
    └ <sqlalchemy.engine.base.Connection object at 0x731651d440a0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ ('job-alice-bob-048', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
    │      │       └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
    │      └ <function AsyncAdapt_asyncmy_cursor.execute at 0x731654ec7d00>
    └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x731651d32bb0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 95, in execute
    return self.await_(self._execute_async(operation, parameters))
           │    │      │    │              │          └ ('job-alice-bob-048', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
           │    │      │    │              └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
           │    │      │    └ <function AsyncAdapt_asyncmy_cursor._execute_async at 0x731654ec7e20>
           │    │      └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x731651d32bb0>
           │    └ <member 'await_' of 'AsyncAdapt_asyncmy_cursor' objects>
           └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x731651d32bb0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           │       │             └ <coroutine object AsyncAdapt_asyncmy_cursor._execute_async at 0x731651d9c660>
           │       └ <attribute 'parent' of 'greenlet.greenlet' objects>
           └ <_AsyncIoGreenlet object at 0x731651e33080 (otid=0x7316557649c0) dead>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
                  └ <_cython_3_0_11.coroutine object at 0x731651d6cc20>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 107, in _execute_async
    result = await self._cursor.execute(operation, parameters)
                   │    │               │          └ ('job-alice-bob-048', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_...
                   │    │               └ 'INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_polic...
                   │    └ <member '_cursor' of 'AsyncAdapt_asyncmy_cursor' objects>
                   └ <sqlalchemy.dialects.mysql.asyncmy.AsyncAdapt_asyncmy_cursor object at 0x731651d32bb0>
  File "asyncmy/cursors.pyx", line 179, in execute
    result = await self._query(query)
  File "asyncmy/cursors.pyx", line 364, in _query
    await conn.query(q)
  File "asyncmy/connection.pyx", line 496, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "asyncmy/connection.pyx", line 684, in _read_query_result
    await result.read()
  File "asyncmy/connection.pyx", line 1071, in read
    first_packet = await self.connection.read_packet()
  File "asyncmy/connection.pyx", line 646, in read_packet
    packet.raise_for_error()
  File "asyncmy/protocol.pyx", line 190, in asyncmy.protocol.MysqlPacket.raise_for_error
    cpdef raise_for_error(self):
  File "asyncmy/protocol.pyx", line 194, in asyncmy.protocol.MysqlPacket.raise_for_error
    errors.raise_mysql_exception(self._data)
    │      └ <cyfunction raise_mysql_exception at 0x731656d4cc70>
    └ <module 'asyncmy.errors' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/asyncmy/errors.cpython...
  File "asyncmy/errors.pyx", line 128, in asyncmy.errors.raise_mysql_exception
    cpdef raise_mysql_exception(bytes data):
          └ <cyfunction raise_mysql_exception at 0x731656d4cc70>
  File "asyncmy/errors.pyx", line 137, in asyncmy.errors.raise_mysql_exception
    raise error_class(errno, err_val)

sqlalchemy.exc.IntegrityError: (asyncmy.errors.IntegrityError) (1062, "Duplicate entry 'job-alice-bob-048' for key 'sys_task.PRIMARY'")
[SQL: INSERT INTO sys_task (task_uid, task_name, task_initiator, task_group, task_yaml, concurrent, cron_expression, misfire_policy, status, run_status, task_progress, priority, create_by, create_time, update_by, update_time, remark) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('job-alice-bob-048', 'task2', 'alice', 'default', '[{"job_uid": "psi3", "job_executor": "default", "invoke_target": "module_task.scheduler_test.job", "job_args": "", "job_kwargs": "", "job_name": "psi ... (162 characters truncated) ... r_test.job", "job_args": "", "job_kwargs": "", "job_name": "psi2", "job_parties": "[\\"party1\\",\\"party2\\"]", "job_dependencies": "[\\"psi3\\"]"}]', '1', '0/10 * * * * ?', '3', '1', 'not started', 0, '0', 'admin', datetime.datetime(2025, 4, 26, 14, 47, 43, 520159), '', datetime.datetime(2025, 4, 26, 14, 47, 43, 520196), 'test')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-04-26 14:47:44.336 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 14:48:45.141 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 14:48:45.143 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 14:48:45.168 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 14:48:45.169 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 14:48:45.177 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 14:48:45.177 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 14:48:45.242 | 9e41ef8d5fab485f9a72a3b98caaee00 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 14:48:45.252 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 14:51:28.066 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 14:51:28.067 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 14:51:28.091 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 14:51:28.092 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 14:51:28.101 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 14:51:28.101 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 14:51:28.143 | 3a409a8337fd4cdf8c4bc9b4040b8285 | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 14:51:28.265 | 3168eed72f824567b246ebda33571561 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 14:51:28.284 | 00592381929a4e178678c23b2729b591 | ERROR    | exceptions.handle:exception_handler:53 - No primary key value supplied for column(s) sys_task.task_uid; per-row ORM Bulk UPDATE by Primary Key requires that records contain primary key values (Background on this error at: https://sqlalche.me/e/20/bupq)
Traceback (most recent call last):

  File "/disc/home/beng003/work/DAGScheduler/.venv/bin/pytest", line 10, in <module>
    sys.exit(console_main())
    │   │    └ <function console_main at 0x7277b47529e0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 201, in console_main
    code = main()
           └ <function main at 0x7277b4752950>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
         │                │      │    │                          └ <_pytest.config.Config object at 0x7277b45a4670>
         │                │      │    └ <HookCaller 'pytest_cmdline_main'>
         │                │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7277b45a47c0>
         │                └ <_pytest.config.Config object at 0x7277b45a4670>
         └ <enum 'ExitCode'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'config': <_pytest.config.Config object at 0x7277b45a4670>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_cmdline_main'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_cmdline_main'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_cmdline_main'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7277b45a4670>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7277b4a16170>
           └ <_pytest.config.PytestPluginManager object at 0x7277b4d9df30>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7277b45a4670>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/s...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7277b47b20e0>
           │            └ <_pytest.config.Config object at 0x7277b45a4670>
           └ <function wrap_session at 0x7277b47b1fc0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session  exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=4>
    │       │            │    └ <_pytest.config.Config object at 0x7277b45a4670>
    │       │            └ <function _main at 0x7277b47b20e0>
    │       └ <ExitCode.OK: 0>
    └ <Session  exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=4>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session  exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=4>
    │      │    └ <HookCaller 'pytest_runtestloop'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7277b45a47c0>
    └ <_pytest.config.Config object at 0x7277b45a4670>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'session': <Session  exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=4>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtestloop'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtestloop'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtestloop'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session  exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=4>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7277b4a16170>
           └ <_pytest.config.PytestPluginManager object at 0x7277b4d9df30>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session  exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=4>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/s...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │                                        │              └ <Function test_camel_to_snake>
    │    │                                        └ <Function test_execute_task>
    │    └ <member 'config' of 'Node' objects>
    └ <Function test_execute_task>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'item': <Function test_execute_task>, 'nextitem': <Function test_camel_to_snake>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_protocol'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_protocol'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_execute_task>, 'nextitem': <Function test_camel_to_snake>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7277b4a16170>
           └ <_pytest.config.PytestPluginManager object at 0x7277b4d9df30>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_execute_task>, <Function test_camel_to_snake>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3....
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
    │               │              └ <Function test_camel_to_snake>
    │               └ <Function test_execute_task>
    └ <function runtestprotocol at 0x7277b47b1360>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ True
    │       │      │               └ <Function test_execute_task>
    │       │      └ <function call_and_report at 0x7277b47b1750>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'tests/test_module_admin/test_controller/test_task_controller.py::test_execute_task' when='setup' outcome='passe...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7277b47b1a20>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: TResult | None = func()
            │                └ <function call_and_report.<locals>.<lambda> at 0x7277aaed39a0>
            └ +TResult
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
            │                 │       └ {}
            │                 └ <Function test_execute_task>
            └ <HookCaller 'pytest_runtest_call'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ False
           │    │         │    │     │    │                  └ {'item': <Function test_execute_task>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_call'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_execute_task>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7277b4a16170>
           └ <_pytest.config.PytestPluginManager object at 0x7277b4d9df30>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_execute_task>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3....
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/runner.py", line 174, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7277b46ce440>
    └ <Function test_execute_task>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/_pytest/python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_execute_task>
    │    └ <property object at 0x7277b4764630>
    └ <Function test_execute_task>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'pyfuncitem': <Function test_execute_task>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_pyfunc_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_pyfunc_call'>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_execute_task>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7277b4a16170>
           └ <_pytest.config.PytestPluginManager object at 0x7277b4d9df30>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_execute_task>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='anyio', plugin=<module 'anyio.pytest_plugin' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/pyth...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/anyio/pytest_plugin.py", line 160, in pytest_pyfunc_call
    runner.run_test(pyfuncitem.obj, testargs)
    │      │        │          │    └ {'async_client': <httpx.AsyncClient object at 0x7277aad347c0>}
    │      │        │          └ <property object at 0x7277b46bd6c0>
    │      │        └ <Function test_execute_task>
    │      └ <function TestRunner.run_test at 0x7277aaed2290>
    └ <anyio._backends._asyncio.TestRunner object at 0x7277aae7d810>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2273, in run_test
    self.get_loop().run_until_complete(
    │    └ <function TestRunner.get_loop at 0x7277aaed1ea0>
    └ <anyio._backends._asyncio.TestRunner object at 0x7277aae7d810>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7277b414dab0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7277b414f5b0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7277b42e2f80>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "/disc/home/beng003/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2200, in _run_tests_and_fixtures
    retval = await coro
                   └ <coroutine object test_execute_task at 0x7277aaeabc30>

  File "/disc/home/beng003/work/DAGScheduler/tests/test_module_admin/test_controller/test_task_controller.py", line 61, in test_execute_task
    response = await async_client.post("/scheduler/task/start?task_uid=test_uid")
                     │            └ <function AsyncClient.post at 0x7277b04145e0>
                     └ <httpx.AsyncClient object at 0x7277aad347c0>

  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1859, in post
    return await self.request(
                 │    └ <function AsyncClient.request at 0x7277b0414040>
                 └ <httpx.AsyncClient object at 0x7277aad347c0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
                 │    │    │             │                      └ <httpx._client.UseClientDefault object at 0x7277b0506d70>
                 │    │    │             └ <httpx._client.UseClientDefault object at 0x7277b0506d70>
                 │    │    └ <Request('POST', 'http://localhost:9099/scheduler/task/start?task_uid=test_uid')>
                 │    └ <function AsyncClient.send at 0x7277b04141f0>
                 └ <httpx.AsyncClient object at 0x7277aad347c0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
                     │    └ <function AsyncClient._send_handling_auth at 0x7277b0414280>
                     └ <httpx.AsyncClient object at 0x7277aad347c0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
                     │    └ <function AsyncClient._send_handling_redirects at 0x7277b0414310>
                     └ <httpx.AsyncClient object at 0x7277aad347c0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
                     │    │                    └ <Request('POST', 'http://localhost:9099/scheduler/task/start?task_uid=test_uid')>
                     │    └ <function AsyncClient._send_single_request at 0x7277b04143a0>
                     └ <httpx.AsyncClient object at 0x7277aad347c0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
                     │         │                    └ <Request('POST', 'http://localhost:9099/scheduler/task/start?task_uid=test_uid')>
                     │         └ <function ASGITransport.handle_async_request at 0x7277b0400a60>
                     └ <httpx.ASGITransport object at 0x7277aad35120>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/httpx/_transports/asgi.py", line 170, in handle_async_request
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ASGITransport.handle_async_request.<locals>.send at 0x7277aac0c700>
          │    │   │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x7277aac0c670>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │    └ <fastapi.applications.FastAPI object at 0x7277b4455d80>
          └ <httpx.ASGITransport object at 0x7277aad35120>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <function ASGITransport.handle_async_request.<locals>.send at 0x7277aac0c700>
                           │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x7277aac0c670>
                           └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function ASGITransport.handle_async_request.<locals>.send at 0x7277aac0c700>
          │    │                │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x7277aac0c670>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7277aad346d0>
          └ <fastapi.applications.FastAPI object at 0x7277b4455d80>
> File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7277aac0c820>
          │    │   │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x7277aac0c670>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │    └ <middlewares.trace_middleware.middle.TraceASGIMiddleware object at 0x7277aad34640>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7277aad346d0>

  File "/disc/home/beng003/work/DAGScheduler/middlewares/trace_middleware/middle.py", line 62, in __call__
    await self.app(scope, handle_outgoing_receive, handle_outgoing_request)
          │    │   │      │                        └ <function TraceASGIMiddleware.__call__.<locals>.handle_outgoing_request at 0x7277aac0c8b0>
          │    │   │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x7277aac0c550>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7277aad34610>
          └ <middlewares.trace_middleware.middle.TraceASGIMiddleware object at 0x7277aad34640>

  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function TraceASGIMiddleware.__call__.<locals>.handle_outgoing_request at 0x7277aac0c8b0>
          │                            │    │    │     │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x7277aac0c550>
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │                            │    │    └ <starlette.requests.Request object at 0x7277aad361a0>
          │                            │    └ <fastapi.routing.APIRouter object at 0x7277b011bf10>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7277aad34610>
          └ <function wrap_app_handling_exceptions at 0x7277b2ad4d30>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7277aac0c940>
          │   │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x7277aac0c550>
          │   └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          └ <fastapi.routing.APIRouter object at 0x7277b011bf10>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7277aac0c940>
          │    │                │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x7277aac0c550>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x7277b011bf10>>
          └ <fastapi.routing.APIRouter object at 0x7277b011bf10>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7277aac0c940>
          │     │      │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x7277aac0c550>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │     └ <function Route.handle at 0x7277b2ad63b0>
          └ APIRoute(path='/scheduler/task/start', name='execute_system_task', methods=['POST'])
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7277aac0c940>
          │    │   │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x7277aac0c550>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │    └ <function request_response.<locals>.app at 0x7277b016a440>
          └ APIRoute(path='/scheduler/task/start', name='execute_system_task', methods=['POST'])
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7277aac0c940>
          │                            │    │        │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x7277aac0c550>
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          │                            │    └ <starlette.requests.Request object at 0x7277aad35150>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x7277aac0c9d0>
          └ <function wrap_app_handling_exceptions at 0x7277b2ad4d30>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7277aac0cca0>
          │   │      └ <function ASGITransport.handle_async_request.<locals>.receive at 0x7277aac0c550>
          │   └ {'type': 'http', 'asgi': {'version': '3.0'}, 'http_version': '1.1', 'method': 'POST', 'headers': [(b'host', b'localhost:9099'...
          └ <function request_response.<locals>.app.<locals>.app at 0x7277aac0c9d0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x7277aad35150>
                     └ <function get_request_handler.<locals>.app at 0x7277b016a4d0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x7277b2ad7eb0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'query_db': <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x7277aad35ff0>, 'task_uid': 'test_uid', 'request': <star...
                 │         └ <function execute_system_task at 0x7277b0169360>
                 └ Dependant(path_params=[], query_params=[ModelField(field_info=Query(PydanticUndefined), name='task_uid', mode='validation')],...

  File "/disc/home/beng003/work/DAGScheduler/module_admin/controller/task_controller.py", line 108, in execute_system_task
    execute_task_result = await TaskService.execute_task_once_services(
                                │           └ <classmethod(<function TaskService.execute_task_once_services at 0x7277b0168940>)>
                                └ <class 'module_admin.service.task_service.TaskService'>

  File "/disc/home/beng003/work/DAGScheduler/module_admin/service/task_service.py", line 201, in execute_task_once_services
    await task_scheduler.add_task(task_info)
          │              │        └ TaskModel(task_uid=None, task_name=None, task_initiator=None, task_group='default', task_yaml=[], concurrent='1', cron_expres...
          │              └ <function TaskSchedulerService.add_task at 0x7277b0168670>
          └ <module_admin.service.job_service.TaskSchedulerService object at 0x7277aad366e0>

  File "/disc/home/beng003/work/DAGScheduler/module_admin/service/job_service.py", line 341, in add_task
    await self.progress_tracker.initialize(task)
          │    │                │          └ TaskModel(task_uid=None, task_name=None, task_initiator=None, task_group='default', task_yaml=[], concurrent='1', cron_expres...
          │    │                └ <function TaskProgressTracker.initialize at 0x7277b0168160>
          │    └ <module_admin.service.job_service.TaskProgressTracker object at 0x7277aad34ca0>
          └ <module_admin.service.job_service.TaskSchedulerService object at 0x7277aad366e0>

  File "/disc/home/beng003/work/DAGScheduler/module_admin/service/job_service.py", line 245, in initialize
    await self._update_db(
          │    └ <function TaskProgressTracker._update_db at 0x7277b01683a0>
          └ <module_admin.service.job_service.TaskProgressTracker object at 0x7277aad34ca0>

  File "/disc/home/beng003/work/DAGScheduler/module_admin/service/job_service.py", line 281, in _update_db
    await TaskDao.edit_task_dao(self.db, {"task_uid": task_uid, **updates})
          │       │             │    │                │           └ {'run_status': 'running', 'task_progress': 0}
          │       │             │    │                └ None
          │       │             │    └ <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x7277aad35ff0>
          │       │             └ <module_admin.service.job_service.TaskProgressTracker object at 0x7277aad34ca0>
          │       └ <classmethod(<function TaskDao.edit_task_dao at 0x7277b06e0820>)>
          └ <class 'module_admin.dao.task_dao.TaskDao'>

  File "/disc/home/beng003/work/DAGScheduler/module_admin/dao/task_dao.py", line 147, in edit_task_dao
    await db.execute(update(SysTask), [task])
          │  │       │      │          └ {'task_uid': None, 'run_status': 'running', 'task_progress': 0}
          │  │       │      └ <class 'module_admin.entity.do.task_do.SysTask'>
          │  │       └ <function update at 0x7277b27a2950>
          │  └ <function AsyncSession.execute at 0x7277b1f11000>
          └ <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x7277aad35ff0>

  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 463, in execute
    result = await greenlet_spawn(
                   └ <function greenlet_spawn at 0x7277b2841ea0>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             │       │       │       └ {'params': [{'task_uid': None, 'run_status': 'running', 'task_progress': 0}], 'execution_options': immutabledict({'prebuffer_...
             │       │       └ (<sqlalchemy.sql.dml.Update object at 0x7277aad37f10>,)
             │       └ <method 'switch' of 'greenlet.greenlet' objects>
             └ <_AsyncIoGreenlet object at 0x7277b019c2c0 (otid=0x7277b28159b0) dead>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
    return self._execute_internal(
           │    └ <function Session._execute_internal at 0x7277b20323b0>
           └ <sqlalchemy.orm.session.Session object at 0x7277aad35d50>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                   │      │                 └ <classmethod(<function BulkORMUpdate.orm_execute_statement at 0x7277b20071c0>)>
                   │      └ <class 'sqlalchemy.orm.bulk_persistence.BulkORMUpdate'>
                   └ typing.Any
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1627, in orm_execute_statement
    result = _bulk_update(
             └ <function _bulk_update at 0x7277b2005f30>
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 357, in _bulk_update
    persistence._emit_update_statements(
    │           └ <function _emit_update_statements at 0x7277b2005990>
    └ <module 'sqlalchemy.orm.persistence' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy...
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 778, in _emit_update_statements
    for (
  File "/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 560, in _collect_update_commands
    raise sa_exc.InvalidRequestError(
          │      └ <class 'sqlalchemy.exc.InvalidRequestError'>
          └ <module 'sqlalchemy.exc' from '/disc/home/beng003/work/DAGScheduler/.venv/lib/python3.10/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.InvalidRequestError: No primary key value supplied for column(s) sys_task.task_uid; per-row ORM Bulk UPDATE by Primary Key requires that records contain primary key values (Background on this error at: https://sqlalche.me/e/20/bupq)
2025-04-26 14:51:28.709 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 14:52:45.897 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 14:52:45.900 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 14:52:45.924 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 14:52:45.925 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 14:52:45.932 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 14:52:45.933 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 14:52:45.971 | 05164c10a5094884ab0cbdc086bdffeb | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 14:52:46.079 | 20134abc4d2d49f18dadd96614fef0a3 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 14:52:46.087 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 14:53:13.565 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 14:53:13.566 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 14:53:13.591 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 14:53:13.592 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 14:53:13.597 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 14:53:13.598 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 14:53:13.640 | a07be98ebb014663afa30928ad47548f | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 14:53:13.690 | 782025a6f01c4228a8680496af264793 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 14:53:13.700 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 14:58:09.792 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 14:58:09.793 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 14:58:09.818 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 14:58:09.819 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 14:58:09.826 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 14:58:09.826 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 14:58:09.869 | 3ec71ddb7bdb458a95c68583bbaf0754 | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 14:58:09.920 | fccc4a669b1b44f782e050e5db0791cf | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 14:58:09.932 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 15:03:44.532 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 15:03:44.534 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 15:03:44.557 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 15:03:44.558 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 15:03:44.565 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 15:03:44.566 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 15:03:44.606 | 6320ae8c2456492c9b943769f2506148 | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 15:03:44.655 | 18cfde51e9a544e2bb03b345f769b8a9 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 15:03:44.666 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 15:07:56.439 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 15:07:56.442 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 15:07:56.466 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 15:07:56.467 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 15:07:56.475 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 15:07:56.476 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 15:07:56.520 | 1ca7961f47f14e79b3b4cfc2e921cdcf | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 15:07:56.572 | 70d59729adc34576a58e28378654c211 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 15:07:56.586 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 15:12:05.941 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 15:12:05.943 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 15:12:05.966 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 15:12:05.967 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 15:12:05.974 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 15:12:05.974 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 15:12:06.041 | ef476296d55a4c5cb5024b27b9459562 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 15:12:06.049 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 15:12:35.302 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 15:12:35.304 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 15:12:35.329 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 15:12:35.330 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 15:12:35.337 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 15:12:35.338 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 15:12:35.382 | e12a663e075f4440b70b17e641701ccc | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 15:12:35.434 | 2ea7569f411f4765975a6f3a9a4f6801 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 15:12:35.444 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 15:14:07.212 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 15:14:07.213 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 15:14:07.237 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 15:14:07.237 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 15:14:07.244 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 15:14:07.244 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 15:14:07.287 | ae7bcbf0045d43eca014cc80e5be454a | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 15:14:07.300 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 15:16:16.045 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 15:16:16.047 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 15:16:16.072 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 15:16:16.074 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 15:16:16.080 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 15:16:16.081 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 15:16:16.127 | eb0df7c4a0594a26a5f8e8b40d3beef8 | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 15:16:16.139 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 15:20:05.172 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 15:20:05.173 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 15:20:05.193 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 15:20:05.193 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 15:20:05.200 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 15:20:05.201 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 15:20:05.245 | 85bb8bf8e5744023bc283ec9692ba0f1 | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 15:20:05.256 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 15:21:15.550 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 15:21:15.552 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 15:21:15.577 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 15:21:15.578 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 15:21:15.583 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 15:21:15.584 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 15:21:15.625 | b9ca053958ae4ec3bfdee2f7100ec3dc | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 15:21:15.673 | 258ca736bf704f88a451a78308693d77 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 15:21:15.684 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 15:23:02.030 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 15:23:02.032 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 15:23:02.056 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 15:23:02.057 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 15:23:02.063 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 15:23:02.064 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 15:23:02.110 | 5c53ce827c5840a5b0de75ef181134d4 | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 15:23:02.123 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 15:23:51.814 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 15:23:51.815 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 15:23:51.839 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 15:23:51.839 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 15:23:51.845 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 15:23:51.845 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 15:23:51.908 | 3ada9babbb334a2687b11ee98d17d87b | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 15:23:51.916 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 15:26:42.724 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 15:26:42.726 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 15:26:42.752 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 15:26:42.753 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 15:26:42.760 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 15:26:42.761 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 15:26:42.804 | 302aadd372f245dc959904a59fe95972 | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 15:26:42.857 | b0621d6da70e4446aef44409a29def10 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 15:26:42.987 | 417ece9f8abd4181b18ba3171f79e60c | INFO     | module_admin.controller.task_controller:execute_system_task:111 - 执行成功
2025-04-26 15:26:43.053 | 22858e98f0d04cc799e786f26c5c06f8 | INFO     | module_admin.controller.task_controller:stop_task:127 - 任务停止成功
2025-04-26 15:26:43.064 | f176b53098924966b6a76e4c91cf00a5 | INFO     | module_admin.controller.task_controller:query_detail_task:33 - 获取task_uid为test_uid的信息成功
2025-04-26 15:26:43.074 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 15:39:49.411 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 15:39:49.412 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 15:39:49.433 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 15:39:49.433 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 15:39:49.440 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 15:39:49.441 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 15:39:49.499 | a3cee2f13ced4c5a903daea433b4dafc | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 15:39:49.593 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 15:40:21.624 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 15:40:21.626 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 15:40:21.652 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 15:40:21.653 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 15:40:21.661 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 15:40:21.663 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 15:40:21.707 | c0e44459ba874327b637b1eb49a8ef3c | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 15:40:21.759 | 172bec87121a46ef96f1bf8a4d98d0db | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 15:40:39.544 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 15:40:56.029 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 15:40:56.031 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 15:40:56.057 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 15:40:56.057 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 15:40:56.065 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 15:40:56.065 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 15:40:56.131 | 3f8f723de5194346a3c7d8e5287fa4f9 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 15:40:56.139 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 15:41:20.876 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 15:41:20.878 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 15:41:20.904 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 15:41:20.904 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 15:41:20.910 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 15:41:20.911 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 15:41:20.953 | d54a0ba44cde41af99ae31bbe8a7b52d | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 15:41:21.006 | 0fb54ec77df04ebda3d1b9acbd293a95 | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 15:41:21.121 | 6cd95c29d40646b8bd0609486bb3b596 | INFO     | module_admin.controller.task_controller:execute_system_task:113 - 执行成功
2025-04-26 15:41:21.186 | 8f6a516b342943678e519e3004ac9b03 | INFO     | module_admin.controller.task_controller:stop_task:130 - 任务停止成功
2025-04-26 15:41:21.198 | d084d6d06347483f945350db08b4a767 | INFO     | module_admin.controller.task_controller:query_detail_task:33 - 获取task_uid为test_uid的信息成功
2025-04-26 15:41:21.208 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
2025-04-26 08:02:37.824 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 08:02:37.824 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 08:03:03.263 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 08:03:03.263 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 08:03:03.461 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 08:03:03.463 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 08:03:03.468 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 08:03:03.469 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 08:11:32.098 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 08:11:32.098 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 11:38:44.902 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 11:38:44.902 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 11:39:02.894 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 11:39:02.895 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 11:39:03.079 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 11:39:03.081 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 11:39:03.087 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 11:39:03.088 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 19:41:44.649 |  | INFO     | server:lifespan:17 - RuoYi-FastAPI开始启动
2025-04-26 19:41:44.652 |  | INFO     | config.get_db:init_create_table:23 - 初始化数据库连接...
2025-04-26 19:41:44.672 |  | INFO     | config.get_db:init_create_table:26 - 数据库连接成功
2025-04-26 19:41:44.672 |  | INFO     | config.get_redis:create_redis_pool:19 - 开始连接redis...
2025-04-26 19:41:44.681 |  | INFO     | config.get_redis:create_redis_pool:32 - redis连接成功
2025-04-26 19:41:44.681 |  | INFO     | server:lifespan:22 - RuoYi-FastAPI启动成功
2025-04-26 19:41:44.725 | 983f0703d0e143d796e7e2ac075b8b0d | INFO     | module_admin.controller.task_controller:get_task_list:56 - 获取成功
2025-04-26 19:41:44.775 | 991a591976794e9a8ff77a932a72b57e | INFO     | module_admin.controller.task_controller:add_task:75 - 新增成功
2025-04-26 19:41:44.912 | afb452dd8f9842fe812929985e2c7369 | INFO     | module_admin.controller.task_controller:execute_system_task:113 - 执行成功
2025-04-26 19:41:44.982 | cd7b5986d3464ae3bcac3b76a51194bd | INFO     | module_admin.controller.task_controller:stop_task:130 - 任务停止成功
2025-04-26 19:41:44.993 | f4111d7a29474664a7085ee39cf484e1 | INFO     | module_admin.controller.task_controller:query_detail_task:33 - 获取task_uid为test_uid的信息成功
2025-04-26 19:41:45.003 |  | INFO     | config.get_redis:close_redis_pool:52 - 关闭redis连接成功
